name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      maria:
        image: mariadb:10.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: site-holding-test
          MYSQL_USER: holding
          MYSQL_PASSWORD: holding
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Generate key
        env:
          DB_DATABASE: site-holding-test
          DB_USERNAME: holding
          DB_PASSWORD: holding
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Setup Migrations
          env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}
          run: php artisan migrate -n


      - name: Execute tests (With Coverage) via PHPUnit
        env:
          DB_DATABASE: site-holding-test
          DB_USERNAME: holding
          DB_PASSWORD: holding
          DB_PORT: ${{ job.services.maria.ports[3306] }}
        run: php artisan test --without-tty --coverage --min=40 --coverage-html=output

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: coverage-html
          path: output
          if-no-files-found: ignore

  code_style:
    name: PSR2 code style check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-interaction --optimize-autoloader

      - name: Run style check
        id: style_check
        run: ./vendor/bin/pint --test
